### ISSUE TITLE
Tracking: Transaction simulator

### ISSUE THREAD

**Issue by chirag-bgh** [lu-bann/taiyi#171]
- [x] Mock tx validator
- [x] Add validation logics
- [x] #105  
- [ ] Simulate against latest state
- [ ] detect conflicts between preconf requests
- [x] #241
