### ISSUE TITLE
Tracking: Metrics

### ISSUE THREAD

**Issue by chirag-bgh** [lu-bann/taiyi#173]
- [x] https://github.com/lu-bann/taiyi/issues/170
- [x] https://github.com/lu-bann/taiyi/issues/169
- [x] https://github.com/lu-bann/taiyi/issues/168
