### ISSUE TITLE
Tracking: On chain delegation

### ISSUE THREAD

**Issue by zsluedem** [lu-bann/taiyi#177]
- [x] https://github.com/lu-bann/taiyi/issues/133
- [x] https://github.com/lu-bann/helix/issues/19
- [x] https://github.com/lu-bann/helix/issues/20
