### ISSUE TITLE
test[tracking]: e2e tests for preconfer

### ISSUE THREAD

**Issue by zsluedem** [lu-bann/taiyi#206]
Thr target of this issue is to add end to end test case to taiyi. Currently, we should only focus on the normal workflow. 

Because testing preconf always interact  with eth network, we decide to use kurtosis to help setting up the testing network. But the current kurtosis ethereum package doesnt set up infra as we want.For example, helix relay and preconf builder are not actually support and we need to support that by our own.

The issues below are for the kurtosis update related tasks.

- [x] Setup helix relay and rbuilder in kurtosis devnet. (done)
- [x] Helix and rbuilder integrate problems https://github.com/lu-bann/taiyi/issues/296 

The issues below are about the test cases we need to implement.

- [x] #299
- [x] Preconf preserve blockspace workflow
- [ ] Preconf tx revert case
- [ ] ~~Preconf blockspace full case~~ (not workable because taiyi consume full block)
